apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-services
  namespace: backend-mainnet
spec:
  podSelector:
    matchLabels:
      tier: api
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: backend-mainnet
    ports:
    - port: 3000
      protocol: TCP
    - port: 3001
      protocol: TCP
    - port: 3002
      protocol: TCP
    - port: 3003
      protocol: TCP
    - port: 3004
      protocol: TCP
    - port: 3005
      protocol: TCP
    - port: 3006
      protocol: TCP
    - port: 3007
      protocol: TCP
    - port: 3008
      protocol: TCP
